/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ul;

import static com.oracle.nio.BufferSecrets.instance;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.Global.instance;
import model.User;

/**
 *
 * @author Clark
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
 User user;
    private Icon person_image;
    public ViewJPanel(User user) {
   this.user = user;
        initComponents();
dispalyUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTxtDOB = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        jAffiliation = new javax.swing.JLabel();
        jCity = new javax.swing.JLabel();
        jTxtAffiliation = new javax.swing.JTextField();
        jTxtDegree1Start = new javax.swing.JTextField();
        jDegree2Start = new javax.swing.JLabel();
        jCareer = new javax.swing.JLabel();
        jDegree2End = new javax.swing.JLabel();
        jTxtDegree2Start = new javax.swing.JTextField();
        jTxtDegree2End = new javax.swing.JTextField();
        jTxtCareer = new javax.swing.JTextField();
        jDegree1End = new javax.swing.JLabel();
        jDegree1 = new javax.swing.JLabel();
        jTxtCity = new javax.swing.JTextField();
        jFirstName = new javax.swing.JLabel();
        jTxtDegree1End = new javax.swing.JTextField();
        jTxtDegree1 = new javax.swing.JTextField();
        jDegree2 = new javax.swing.JLabel();
        jDegree1Start = new javax.swing.JLabel();
        jTxtDegree2 = new javax.swing.JTextField();
        jPhoto = new javax.swing.JLabel();
        jMajor = new javax.swing.JLabel();
        jStreetLine1 = new javax.swing.JLabel();
        jTxtMajor = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtStreetLine1 = new javax.swing.JTextField();
        jTxtFirstName = new javax.swing.JTextField();
        jAge = new javax.swing.JLabel();
        jCountry = new javax.swing.JLabel();
        jLastName = new javax.swing.JLabel();
        jTxtAge = new javax.swing.JTextField();
        jStreetLine2 = new javax.swing.JLabel();
        jTxtLastName = new javax.swing.JTextField();
        jTelephone = new javax.swing.JLabel();
        jTxtCountry = new javax.swing.JTextField();
        jDOB = new javax.swing.JLabel();
        jTxtTelephone = new javax.swing.JTextField();
        jTxtStreetLine2 = new javax.swing.JTextField();
        lbl_img = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View User");

        jEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jEmail.setText("Email");

        jAffiliation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jAffiliation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jAffiliation.setText("Affiliation");

        jCity.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCity.setText("City");

        jDegree2Start.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDegree2Start.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jDegree2Start.setText("Degree 2 Start");

        jCareer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCareer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCareer.setText("Career");

        jDegree2End.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDegree2End.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jDegree2End.setText("Degree 2 End");

        jTxtDegree2End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDegree2EndActionPerformed(evt);
            }
        });

        jTxtCareer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCareerActionPerformed(evt);
            }
        });

        jDegree1End.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDegree1End.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jDegree1End.setText("Degree 1 End");

        jDegree1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDegree1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jDegree1.setText("Degree 1");

        jFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jFirstName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jFirstName.setText("First Name");

        jTxtDegree1End.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtDegree1EndActionPerformed(evt);
            }
        });

        jDegree2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDegree2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jDegree2.setText("Degree 2");

        jDegree1Start.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDegree1Start.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jDegree1Start.setText("Degree 1 Start");

        jPhoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPhoto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPhoto.setText("Photo");

        jMajor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jMajor.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jMajor.setText("Major");

        jStreetLine1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jStreetLine1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jStreetLine1.setText("Street Line 1");

        jTxtStreetLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtStreetLine1ActionPerformed(evt);
            }
        });

        jTxtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFirstNameActionPerformed(evt);
            }
        });

        jAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jAge.setText("Age");

        jCountry.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCountry.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCountry.setText("Country");

        jLastName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLastName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLastName.setText("Last Name");

        jTxtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtAgeActionPerformed(evt);
            }
        });

        jStreetLine2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jStreetLine2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jStreetLine2.setText("Street Line 2");

        jTelephone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTelephone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTelephone.setText("Telephone");

        jTxtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCountryActionPerformed(evt);
            }
        });

        jDOB.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jDOB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jDOB.setText("DOB");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 636, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                    .addComponent(jAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtAge)
                                    .addComponent(jTxtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLastName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTxtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                                    .addComponent(jTxtLastName))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jAffiliation, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jCountry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtCountry)
                                        .addComponent(jTxtAffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jStreetLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jStreetLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtStreetLine1)
                                        .addComponent(jTxtStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDegree1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCareer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDegree1Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtDegree1Start, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtCareer)
                                        .addComponent(jTxtDegree1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jDegree2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDegree2Start, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jDegree2End, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDegree1End, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtDegree2Start, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtDegree1End)
                                        .addComponent(jTxtDegree2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTxtDegree2End, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(131, 131, 131)))
                    .addGap(57, 57, 57)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jFirstName)
                                        .addComponent(jTxtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLastName)
                                        .addComponent(jTxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDOB))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jAge)
                                        .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTelephone)
                                        .addComponent(jTxtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jEmail))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jStreetLine1)
                                        .addComponent(jTxtStreetLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jCareer)
                                        .addComponent(jTxtCareer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jDegree1)
                                        .addComponent(jTxtDegree1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxtDegree1Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDegree1Start))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jDegree1End)
                                        .addComponent(jTxtDegree1End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jDegree2)
                                        .addComponent(jTxtDegree2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jTxtDegree2Start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jDegree2Start))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jDegree2End)
                                        .addComponent(jTxtDegree2End, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jStreetLine2)
                                .addComponent(jTxtStreetLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPhoto, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jCity))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jCountry)
                        .addComponent(jTxtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jAffiliation)
                        .addComponent(jTxtAffiliation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTxtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jMajor))
                    .addContainerGap(92, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtDegree2EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDegree2EndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDegree2EndActionPerformed

    private void jTxtCareerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCareerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCareerActionPerformed

    private void jTxtDegree1EndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtDegree1EndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtDegree1EndActionPerformed

    private void jTxtStreetLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtStreetLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtStreetLine1ActionPerformed

    private void jTxtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFirstNameActionPerformed

    private void jTxtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtAgeActionPerformed

    private void jTxtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCountryActionPerformed

public void dispalyUser() {
jTxtFirstName.setText(user.getFirstName());
jTxtLastName.setText(user.getLastName());
jTxtDOB.setText(user.getDob());
jTxtAge.setText(user.getAge());
jTxtTelephone.setText(user.getTelephoneNumber());
jTxtEmail.setText(user.getEmail());
jTxtStreetLine1.setText(user.getStreetLine1());
jTxtStreetLine2.setText(user.getStreetLine2());
jTxtCity.setText(user.getCity());
jTxtCountry.setText(user.getCountry());
jTxtAffiliation.setText(user.getAffiliation());
jTxtMajor.setText(user.getMajor());
jTxtCareer.setText(user.getCareer());
jTxtDegree1.setText(user.getDegree1());
jTxtDegree1Start.setText(user.getDegree1Start());
jTxtDegree1End.setText(user.getDegree1End());
jTxtDegree2.setText(user.getDegree2());
jTxtDegree2Start.setText(user.getDegree2Start());
jTxtDegree2End.setText(user.getDegree2End());
Icon icon = new ImageIcon(user.getPhoto());
lbl_img.setIcon(icon);
lbl_img.setVisible(true);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAffiliation;
    private javax.swing.JLabel jAge;
    private javax.swing.JLabel jCareer;
    private javax.swing.JLabel jCity;
    private javax.swing.JLabel jCountry;
    private javax.swing.JLabel jDOB;
    private javax.swing.JLabel jDegree1;
    private javax.swing.JLabel jDegree1End;
    private javax.swing.JLabel jDegree1Start;
    private javax.swing.JLabel jDegree2;
    private javax.swing.JLabel jDegree2End;
    private javax.swing.JLabel jDegree2Start;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jFirstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLastName;
    private javax.swing.JLabel jMajor;
    private javax.swing.JLabel jPhoto;
    private javax.swing.JLabel jStreetLine1;
    private javax.swing.JLabel jStreetLine2;
    private javax.swing.JLabel jTelephone;
    private javax.swing.JTextField jTxtAffiliation;
    private javax.swing.JTextField jTxtAge;
    private javax.swing.JTextField jTxtCareer;
    private javax.swing.JTextField jTxtCity;
    private javax.swing.JTextField jTxtCountry;
    private javax.swing.JTextField jTxtDOB;
    private javax.swing.JTextField jTxtDegree1;
    private javax.swing.JTextField jTxtDegree1End;
    private javax.swing.JTextField jTxtDegree1Start;
    private javax.swing.JTextField jTxtDegree2;
    private javax.swing.JTextField jTxtDegree2End;
    private javax.swing.JTextField jTxtDegree2Start;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtFirstName;
    private javax.swing.JTextField jTxtLastName;
    private javax.swing.JTextField jTxtMajor;
    private javax.swing.JTextField jTxtStreetLine1;
    private javax.swing.JTextField jTxtStreetLine2;
    private javax.swing.JTextField jTxtTelephone;
    private javax.swing.JLabel lbl_img;
    // End of variables declaration//GEN-END:variables
}
