/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ul;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

import model.Employee;
import model.EmployeeHistory;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import sun.security.jca.GetInstance.Instance;

/**
 *
 * @author Clark
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
String filename = null;
byte[] person_image = null;
ImageIcon icon;


EmployeeHistory history;

    public CreateJPanel(EmployeeHistory history) {
     this.history = history;
        initComponents();
    }
////
Employee employee;
   public CreateJPanel(Employee employee) {
     this.employee = employee;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jAge = new javax.swing.JLabel();
        jTxtAge = new javax.swing.JTextField();
        jLevel = new javax.swing.JLabel();
        jTxtLevel = new javax.swing.JTextField();
        jSaveButton = new javax.swing.JButton();
        jTxtEmailAddress = new javax.swing.JTextField();
        jTeamInfo = new javax.swing.JLabel();
        jTxtTeamInfo = new javax.swing.JTextField();
        jCelePhone = new javax.swing.JLabel();
        jTxtCellPhone = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        jTxtStartDate = new javax.swing.JTextField();
        jEmployeeID = new javax.swing.JLabel();
        jTxtEmployeeID = new javax.swing.JTextField();
        jPositionDate = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jTxtPositionTitle = new javax.swing.JTextField();
        jTxtGender = new javax.swing.JTextField();
        jStartDate = new javax.swing.JLabel();
        jPhoto = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setAlignmentX(0.7F);
        setAlignmentY(0.7F);
        setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(896, 849));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Profile");
        jLabel1.setMaximumSize(new java.awt.Dimension(65, 14));

        jName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jName.setText("Name");

        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });

        jAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jAge.setText("Age");

        jLevel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLevel.setText("Level");

        jSaveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSaveButton.setText("Save");
        jSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSaveButtonActionPerformed(evt);
            }
        });

        jTeamInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTeamInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTeamInfo.setText("Team Info");

        jTxtTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTeamInfoActionPerformed(evt);
            }
        });

        jCelePhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCelePhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCelePhone.setText("CellPhone");

        jEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jEmail.setText("EmailAddress");

        jEmployeeID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jEmployeeID.setText("Employee ID");

        jTxtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmployeeIDActionPerformed(evt);
            }
        });

        jPositionDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPositionDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPositionDate.setText("Position Title");

        jGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jGender.setText("Gender");

        jTxtPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPositionTitleActionPerformed(evt);
            }
        });

        jStartDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jStartDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jStartDate.setText("Start Date");

        jPhoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPhoto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPhoto.setText("Photo");

        btnImage.setText("choose");
        btnImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImageMouseClicked(evt);
            }
        });
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contact Info");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jCelePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTeamInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTxtTeamInfo)
                                        .addComponent(jTxtCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jAge, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmployeeID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jStartDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTxtEmployeeID)
                                .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSaveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPositionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnImage))))
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jName)
                            .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAge)
                            .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLevel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTeamInfo)
                            .addComponent(jTxtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCelePhone)
                            .addComponent(jTxtCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jEmployeeID)
                            .addComponent(jTxtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jGender)
                            .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jStartDate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPositionDate)
                            .addComponent(jTxtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnImage)
                                .addGap(87, 87, 87)
                                .addComponent(jSaveButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jPhoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(493, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2});

    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNameActionPerformed

    private void jSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSaveButtonActionPerformed
        // TODO add your handling code here:
//employee.setAge(jTxtAge.getText());// use another way to get value in the lable
//String Age = jTxtAge.getText();// use another way to get value in the lable
//employee.setCellPhonenumber(jTxtCellPhone.getText());
//employee.setEmailAddress(jTxtEmailAddress.getText());
//employee.setEmployeeID(jTxtEmployeeID.getText());
//employee.setGender(jTxtGender.getText());  
//employee.setLevel(jTxtLevel.getText());  
//employee.setName(jTxtName.getText()); 
//employee.setPositionTitle(jTxtPositionTitle.getText());
//employee.setStartDate(jTxtStartDate.getText());
//employee.setTeamInfo(jTxtTeamInfo.getText());

Employee employee = history.addNewEmployee();
employee.setAge(jTxtAge.getText());
employee.setCellPhonenumber(jTxtCellPhone.getText());
employee.setEmailAddress(jTxtEmailAddress.getText());
employee.setEmployeeID(jTxtEmployeeID.getText());
employee.setGender(jTxtGender.getText());  
employee.setLevel(jTxtLevel.getText());  
employee.setName(jTxtName.getText()); 
employee.setPositionTitle(jTxtPositionTitle.getText());
employee.setStartDate(jTxtStartDate.getText());
employee.setTeamInfo(jTxtTeamInfo.getText());
employee.setPhoto(lbl_img.getIcon().toString());
//lbl_img.setIcon(icon);

//lbl_img.getIcon();//path

//System.out.println(lbl_img.getIcon());//path


JOptionPane.showMessageDialog(this,"New Employee Information is added");


jTxtAge.setText("");
jTxtCellPhone.setText("");
jTxtEmailAddress.setText("");
jTxtEmployeeID.setText("");
jTxtGender.setText("");  
jTxtLevel.setText("");  
jTxtName.setText(""); 
jTxtPositionTitle.setText("");
jTxtStartDate.setText("");
jTxtTeamInfo.setText("");
lbl_img.setIcon(null);


//     user.setFirstName(jTxtFirstName.getText());
//     user.setLastName(jTxtLastName.getText());
//     user.setDob(jTxtDOB.getText());
//     user.setAge(jTxtAge.getText());
//     user.setTelephoneNumber(jTxtTelephone.getText());
//     user.setEmail(jTxtEmail.getText());
//     user.setStreetLine1(jTxtStreetLine1.getText());
//     user.setStreetLine2(jTxtStreetLine2.getText());
//     user.setCity(jTxtCity.getText());
//     user.setCountry(jTxtCountry.getText());
//     user.setAffiliation(jTxtAffiliation.getText());
//     user.setMajor(jTxtMajor.getText());
//     user.setCareer(jTxtCareer.getText());
//     user.setDegree1(jTxtDegree1.getText());
//     user.setDegree1Start(jTxtDegree1Start.getText());
//     user.setDegree1End(jTxtDegree1End.getText());
//     user.setDegree2(jTxtDegree2.getText());
//     user.setDegree2Start(jTxtDegree2Start.getText());
//     user.setDegree2End(jTxtDegree2End.getText());
//     user.setImageIcon(icon);
// byte[] img =(user.getImage());
//ImageIcon imageIcon = new ImageIcon(new ImageIcon(img).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
//lbl_img.setIcon(imageIcon);

//JFileChooser chooser = new JFileChooser();
//chooser.showOpenDialog(null);
//File f = chooser.getSelectedFile();
//filename = f.getAbsolutePath();
//ImageIcon imageIcon = new ImageIcon(new ImageIcon(filename).getImage().getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH));
//lbl_img.setIcon(imageIcon);
//Image img =imageIcon.getImage();
//Image imgScale = img.getScaledInstance(lbl_img.getWidth(), lbl_img.getHeight(), Image.SCALE_SMOOTH);
//ImageIcon scaleIcon = new ImageIcon(imgScale);
//lbl_img.setIcon(scaleIcon);
//
//
//try{
//File image = new File(filename);
//FileInputStream fis = new FileInputStream(image);
//ByteArrayOutputStream bos = new ByteArrayOutputStream();
//byte[] buf = new byte[1024];
//for(int readNum; (readNum=fis.read(buf))!=-1;){
//bos.write(buf,0,readNum);
//}
//person_image=bos.toByteArray();
//}catch (Exception e) {
//JOptionPane.showMessageDialog(null,e);
//}




    }//GEN-LAST:event_jSaveButtonActionPerformed

    private void jTxtTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTeamInfoActionPerformed

    private void jTxtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmployeeIDActionPerformed

    private void jTxtPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPositionTitleActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
JFileChooser chooser = new JFileChooser();
chooser.showOpenDialog(null);
chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
String filepath = chooser.getSelectedFile().getPath();//System.out.println(filepath);
//employee.setPhoto(filepath);
//employee.setPhoto(filepath);
Icon icon= new ImageIcon(filepath);
lbl_img.setIcon(icon);
//System.out.println(ImageIcon);



    }//GEN-LAST:event_btnImageActionPerformed

    private void btnImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImageMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImageMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImage;
    private javax.swing.JLabel jAge;
    private javax.swing.JLabel jCelePhone;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jEmployeeID;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jPhoto;
    private javax.swing.JLabel jPositionDate;
    private javax.swing.JButton jSaveButton;
    private javax.swing.JLabel jStartDate;
    private javax.swing.JLabel jTeamInfo;
    private javax.swing.JTextField jTxtAge;
    private javax.swing.JTextField jTxtCellPhone;
    private javax.swing.JTextField jTxtEmailAddress;
    private javax.swing.JTextField jTxtEmployeeID;
    private javax.swing.JTextField jTxtGender;
    private javax.swing.JTextField jTxtLevel;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtPositionTitle;
    private javax.swing.JTextField jTxtStartDate;
    private javax.swing.JTextField jTxtTeamInfo;
    private javax.swing.JLabel lbl_img;
    // End of variables declaration//GEN-END:variables




}
