/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ul;

import static com.oracle.nio.BufferSecrets.instance;
import java.awt.Component;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import static javax.management.Query.value;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.objects.Global.instance;
import model.EmployeeHistory;
import model.Employee;

/**
 *
 * @author Clark
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
EmployeeHistory history;
    private Icon person_image;
    private Employee employee;
    public ViewJPanel(EmployeeHistory history) {
   
        initComponents();
        this.history = history;
        populateTable();

dispalyEmployee();
    }
   public ViewJPanel(Employee employee) {
   
        initComponents();
        this.employee = employee;
        populateTable();

dispalyEmployee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPhoto = new javax.swing.JLabel();
        lbl_img = new javax.swing.JLabel();
        jTxtEmployeeID = new javax.swing.JTextField();
        jPositionDate = new javax.swing.JLabel();
        jGender = new javax.swing.JLabel();
        jTxtPositionTitle = new javax.swing.JTextField();
        jTxtGender = new javax.swing.JTextField();
        jStartDate = new javax.swing.JLabel();
        jName = new javax.swing.JLabel();
        jTxtName = new javax.swing.JTextField();
        jAge = new javax.swing.JLabel();
        jTxtAge = new javax.swing.JTextField();
        jTxtStartDate = new javax.swing.JTextField();
        jLevel = new javax.swing.JLabel();
        jTxtLevel = new javax.swing.JTextField();
        jEmployeeID = new javax.swing.JLabel();
        jTeamInfo = new javax.swing.JLabel();
        jTxtTeamInfo = new javax.swing.JTextField();
        jTxtCellPhone = new javax.swing.JTextField();
        jEmail = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtEmailAddress = new javax.swing.JTextField();
        jCelePhone = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        jBTview = new javax.swing.JButton();
        jBTdelete = new javax.swing.JButton();
        jBTupdate = new javax.swing.JButton();
        jBTsearch = new javax.swing.JButton();
        jTxtSearch = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Employee");

        jPhoto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPhoto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPhoto.setText("Photo");

        jTxtEmployeeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmployeeIDActionPerformed(evt);
            }
        });

        jPositionDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPositionDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPositionDate.setText("Position Title");

        jGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jGender.setText("Gender");

        jTxtPositionTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPositionTitleActionPerformed(evt);
            }
        });

        jStartDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jStartDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jStartDate.setText("Start Date");

        jName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jName.setText("Name");

        jTxtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNameActionPerformed(evt);
            }
        });

        jAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jAge.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jAge.setText("Age");

        jLevel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLevel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLevel.setText("Level");

        jEmployeeID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEmployeeID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jEmployeeID.setText("Employee ID");

        jTeamInfo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTeamInfo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jTeamInfo.setText("Team Info");

        jTxtTeamInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtTeamInfoActionPerformed(evt);
            }
        });

        jEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jEmail.setText("EmailAddress");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contact Info");

        jCelePhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCelePhone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jCelePhone.setText("CellPhone");

        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Age", "EmployeeID", "Cellphone", "EmailAddress", "Gender", "Level", "TeamInfo", "StartDate", "PositionTitle", "Photo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        jBTview.setText("View");
        jBTview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTviewActionPerformed(evt);
            }
        });

        jBTdelete.setText("Delete");
        jBTdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTdeleteActionPerformed(evt);
            }
        });

        jBTupdate.setText("Update");
        jBTupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBTupdateActionPerformed(evt);
            }
        });

        jBTsearch.setText("Search");

        jTxtSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTxtSearchMouseReleased(evt);
            }
        });
        jTxtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtSearchActionPerformed(evt);
            }
        });
        jTxtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(93, 93, 93)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jAge, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jName, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addContainerGap()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jTeamInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLevel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jBTview)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBTdelete)))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBTupdate)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jGender, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPositionDate, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addComponent(jBTsearch)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jCelePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtEmailAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtCellPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(98, 98, 98)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(144, 144, 144))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTxtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(112, 112, 112))))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBTdelete, jBTview});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTview)
                    .addComponent(jBTdelete)
                    .addComponent(jBTupdate)
                    .addComponent(jBTsearch)
                    .addComponent(jTxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jName)
                    .addComponent(jTxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jEmployeeID)
                    .addComponent(jTxtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAge)
                    .addComponent(jTxtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jGender)
                    .addComponent(jTxtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLevel))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTeamInfo)
                            .addComponent(jTxtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPositionDate)
                            .addComponent(jTxtPositionTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jStartDate)
                        .addComponent(jTxtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPhoto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCellPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCelePhone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jEmail)))
                    .addComponent(lbl_img, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtEmployeeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmployeeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmployeeIDActionPerformed

    private void jTxtPositionTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPositionTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPositionTitleActionPerformed

    private void jTxtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNameActionPerformed

    private void jTxtTeamInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtTeamInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtTeamInfoActionPerformed




    private void jBTviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTviewActionPerformed
        // TODO add your handling code here:
 DefaultTableModel model =(DefaultTableModel) tblEmployee.getModel();
 int selectedRowIndex = tblEmployee.getSelectedRow();
  if (selectedRowIndex < 0) {
         JOptionPane.showMessageDialog(this,"Please select a row to view!!");
         return;
        }

jTxtName.setText(model.getValueAt(selectedRowIndex,0).toString());
jTxtAge.setText(model.getValueAt(selectedRowIndex,1).toString());
jTxtEmployeeID.setText(model.getValueAt(selectedRowIndex,2).toString());
jTxtCellPhone.setText(model.getValueAt(selectedRowIndex,3).toString());
jTxtEmailAddress.setText(model.getValueAt(selectedRowIndex,4).toString());
jTxtGender.setText(model.getValueAt(selectedRowIndex,5).toString());
jTxtLevel.setText(model.getValueAt(selectedRowIndex,6).toString());
jTxtTeamInfo.setText(model.getValueAt(selectedRowIndex,7).toString());
jTxtStartDate.setText(model.getValueAt(selectedRowIndex,8).toString());
jTxtPositionTitle.setText(model.getValueAt(selectedRowIndex,9).toString());
//jPhoto.setText(model.getValueAt(selectedRowIndex,10).toString());//get path
Icon icon= new ImageIcon( (String) model.getValueAt(selectedRowIndex,10));
lbl_img.setIcon(icon);
lbl_img.setVisible(true);
//tblEmployee.getColumn("Photo").setCellRenderer(new myTableCellRenderer());



//Icon icon = new ImageIcon(model.getValueAt(selectedRowIndex,10).toString());
//lbl_img.setIcon(icon);
//lbl_img.setVisible(true);
//lbl_img.setText(model.getValueAt(selectedRowIndex,10).toString());


//jTxtLevel.setText(selectedEmp.getLevel());


    }//GEN-LAST:event_jBTviewActionPerformed

    private void jBTdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTdeleteActionPerformed
        // TODO add your handling code here:
 DefaultTableModel model =(DefaultTableModel) tblEmployee.getModel();
      
    try{
      int selectedRowIndex = tblEmployee.getSelectedRow();
  if (selectedRowIndex < 0) {
         JOptionPane.showMessageDialog(this,"Please select a row to delete!!");
         return;
        }
      model.removeRow(selectedRowIndex);
}catch(Exception ex)
{
JOptionPane.showMessageDialog(null,ex);
}
//System.out.println("===============00000==============");
//System.out.println(selectedRowIndex);   
//System.out.println(tblEmployee.getModel());
//System.out.println("===============11111==============");
//System.out.println((DefaultTableModel) tblEmployee.getModel());
//System.out.println("==============22222===============");
//System.out.println( tblEmployee.getModel().toString());
////System.out.println((Employee)model.getValueAt(selectedRowIndex, 0).toString());
//
//model.getValueAt(selectedRowIndex, 0).toString();
//System.out.println("==============333333333==============");
//System.out.println(model.getValueAt(selectedRowIndex, 0).toString());
//     Employee selectedEmp = (Employee)model.getValueAt(selectedRowIndex, 0);


      //history.deleteEmp(selectedEmp);
     JOptionPane.showMessageDialog(this,"The employee info has delete!!");
    // populateTable();
    }//GEN-LAST:event_jBTdeleteActionPerformed

    private void jBTupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTupdateActionPerformed
        // TODO add your handling code here:
   int i = tblEmployee.getSelectedRow();
DefaultTableModel model =(DefaultTableModel) tblEmployee.getModel();
  if (i>=  0) {

           model.setValueAt(jTxtName.getText(),i,0);
           model.setValueAt(jTxtAge.getText(),i,1);
model.setValueAt(jTxtEmployeeID.getText(),i,2);
model.setValueAt(jTxtCellPhone.getText(),i,3);
model.setValueAt(jTxtEmailAddress.getText(),i,4);
model.setValueAt(jTxtGender.getText(),i,5);
model.setValueAt(jTxtLevel.getText(),i,6);
model.setValueAt(jTxtTeamInfo.getText(),i,7);
model.setValueAt(jTxtStartDate.getText(),i,8);
model.setValueAt(jTxtPositionTitle.getText(),i,9);
model.setValueAt(jPhoto.getText(),i,10);
//Icon icon = new ImageIcon(employee.getPhoto());
//lbl_img.setIcon(icon);
//model.setValueAt(lbl_img.getText(),i,10);



}
else{

         JOptionPane.showMessageDialog(null,"error");

        }





    }//GEN-LAST:event_jBTupdateActionPerformed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
        // TODO add your handling code here:
DefaultTableModel model =(DefaultTableModel) tblEmployee.getModel();
 int selectedRowIndex = tblEmployee.getSelectedRow();

jTxtName.setText(model.getValueAt(selectedRowIndex,0).toString());
jTxtAge.setText(model.getValueAt(selectedRowIndex,1).toString());
jTxtEmployeeID.setText(model.getValueAt(selectedRowIndex,2).toString());
jTxtCellPhone.setText(model.getValueAt(selectedRowIndex,3).toString());
jTxtEmailAddress.setText(model.getValueAt(selectedRowIndex,4).toString());
jTxtGender.setText(model.getValueAt(selectedRowIndex,5).toString());
jTxtLevel.setText(model.getValueAt(selectedRowIndex,6).toString());
jTxtTeamInfo.setText(model.getValueAt(selectedRowIndex,7).toString());
jTxtStartDate.setText(model.getValueAt(selectedRowIndex,8).toString());
jTxtPositionTitle.setText(model.getValueAt(selectedRowIndex,9).toString());

    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void jTxtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSearchActionPerformed

    private void jTxtSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtSearchMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtSearchMouseReleased

    private void jTxtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtSearchKeyReleased
        // TODO add your handling code here:
DefaultTableModel table =(DefaultTableModel) tblEmployee.getModel();
String search = jTxtSearch.getText().toLowerCase();
TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
tblEmployee.setRowSorter(tr);
tr.setRowFilter(RowFilter.regexFilter(search));

    }//GEN-LAST:event_jTxtSearchKeyReleased

public void dispalyEmployee() {
DefaultTableModel model =(DefaultTableModel) tblEmployee.getModel();
 int selectedRowIndex = tblEmployee.getSelectedRow();
//
//jTxtName.setText(model.getValueAt(selectedRowIndex,0).toString());
//jTxtAge.setText(model.getValueAt(selectedRowIndex,1).toString());
//jTxtEmployeeID.setText(model.getValueAt(selectedRowIndex,2).toString());
//jTxtCellPhone.setText(model.getValueAt(selectedRowIndex,3).toString());
//jTxtEmailAddress.setText(model.getValueAt(selectedRowIndex,4).toString());
//jTxtGender.setText(model.getValueAt(selectedRowIndex,5).toString());
//jTxtLevel.setText(model.getValueAt(selectedRowIndex,6).toString());
//jTxtTeamInfo.setText(model.getValueAt(selectedRowIndex,7).toString());
//jTxtStartDate.setText(model.getValueAt(selectedRowIndex,8).toString());
//jTxtPositionTitle.setText(model.getValueAt(selectedRowIndex,9).toString());
////Icon icon = new ImageIcon(model.getValueAt(selectedRowIndex,10).toString());
////Icon icon = new ImageIcon(employee.getPhoto());
//lbl_img.setIcon(icon);
//lbl_img.setVisible(true);
//System.out.println(model.getValueAt(selectedRowIndex,10).toString());
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAge;
    private javax.swing.JButton jBTdelete;
    private javax.swing.JButton jBTsearch;
    private javax.swing.JButton jBTupdate;
    private javax.swing.JButton jBTview;
    private javax.swing.JLabel jCelePhone;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jEmployeeID;
    private javax.swing.JLabel jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLevel;
    private javax.swing.JLabel jName;
    private javax.swing.JLabel jPhoto;
    private javax.swing.JLabel jPositionDate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jStartDate;
    private javax.swing.JLabel jTeamInfo;
    private javax.swing.JTextField jTxtAge;
    private javax.swing.JTextField jTxtCellPhone;
    private javax.swing.JTextField jTxtEmailAddress;
    private javax.swing.JTextField jTxtEmployeeID;
    private javax.swing.JTextField jTxtGender;
    private javax.swing.JTextField jTxtLevel;
    private javax.swing.JTextField jTxtName;
    private javax.swing.JTextField jTxtPositionTitle;
    private javax.swing.JTextField jTxtSearch;
    private javax.swing.JTextField jTxtStartDate;
    private javax.swing.JTextField jTxtTeamInfo;
    private javax.swing.JLabel lbl_img;
    private javax.swing.JTable tblEmployee;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {

        DefaultTableModel model =(DefaultTableModel) tblEmployee.getModel();
        model.setRowCount(0);
        for( Employee emp : history.getHistory()){

           Object [] row = new  Object[11];
            row[0] = emp.getName();
            row[1] = emp.getAge();
            row[2] = emp.getEmployeeID();
            row[3] = emp.getCellPhonenumber();
            row[4] = emp.getEmailAddress();
            row[5] = emp.getGender();
            row[6] = emp.getLevel();
            row[7] = emp.getPositionTitle();
            row[8] = emp.getStartDate();
            row[9] = emp.getTeamInfo();
            row[10] = emp.getPhoto();

            model.addRow(row); 

              }

        }


}
